### ISSUE TITLE
Spurious errors from extra-project Haskell files.

### ISSUE THREAD

**Issue by friedbrice** [haskell/vscode-haskell#376]
I have some Haskell files in my project directory outside of the traditional `./src/`, `./app/` and `./test/` directories. Examples are `./dev-tools.hs` where I keep some things I like to use in GHCi, and `./.cache/hie-bios/.../Paths_mwb.hs`.

Haskell plugin reports errors in these files and tries to set up a multi-cradle project, but I would prefer if it didn't since they are not part of my actual project source.

Is there a way to tell the plugin to only trigger for Haskell files in specific directories?

**Comment by ilyakooo0** [comment]
I think defining an explicit `hie.yaml` will restrict HLS to the specified directories.

**Comment by ilyakooo0** [comment]
This might be helpful for generating the file: https://github.com/Avi-D-coder/implicit-hie

**Comment by friedbrice** [comment]
Thanks, @ilyakooo0! I actually tried this, following the advice on their readme (https://github.com/mpickering/hie-bios#ignoring-directories-1).

My config looked like this:

```
cradle:
  multi:
    - path: "./.cache"
      config:
        cradle:
          none:
    - path: "./"
      config:
        cradle:
          cabal:
            - path: "./src"
              component: ...
            - path: "./app"
              component: ...
            - path: "./test"
              component: ...
```

Unfortunately, when I closed and restarted VS Code, vscode-haskell complained that it could not determine the appropriate GHC version :-/

**Comment by friedbrice** [comment]
This is what I'm seeing every time I open my project:

<img width="919" alt="Screen Shot 2021-04-09 at 1 00 30 PM" src="https://user-images.githubusercontent.com/3302003/114234488-ad9c1000-9933-11eb-8e4d-1375375e51da.png">

Here are my config files:

* hie.yaml

```
cradle:
 cabal:
  - path: "./src"
    component: ...
  - path: "./test"
    component: ...
  - path: "./app"
    component: ...
  - path: "./one-off-task"
    component: ...
```

* .vscode/settings.json

```
{
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "editor.tabSize": 2,
  "haskell.formattingProvider": "ormolu",
  "haskell.formatOnImportOn": true,
  "nixEnvSelector.nixFile": "${workspaceRoot}/shell.nix",
}
```
