### ISSUE TITLE
Running HLS features on a standalone Haskell script 

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/vscode-haskell#613]
Having a following script:

```haskell
#!/usr/bin/env cabal
{- cabal:
build-depends: base
            , split
-}

import Data.List.Split (splitOn)

main :: IO ()
main = do
  let orders = splitOn "x" "axbxc"
  putStrLn $ head orders
```

I want to be able to have HLS features on this script.
Is it possible in any way?

**Comment by fendor** [comment]
Hi! Unfortunately, this is not possible at the moment. You might be able to get a similar result by using `cabal install --lib base split --package-env=.` and creating a `hie.yaml` file with the  contents:
```yaml
cradle:
  direct:
    arguments:
      - -package-env
      -.ghc.environment.x86_64-linux-<version> # check what file has been generated after `cabal install --lib --package-env=.`
      - Script.hs
``` 
 
Native support ticket: https://github.com/haskell/hie-bios/issues/217
